### ISSUE TITLE
JWT `aud` Claim Does Not Match JWT Spec

### ISSUE THREAD

**Issue by juriadams** [pilcrowOnPaper/oslo#14]
Upon reviewing the `oslo` module, I've found its features compelling and plan on integrating it into our production applications. However, I've noticed an inconsistency concerning the `oslo/jwt` not completely adhering to the JWT spec.

According to [Section 4.1.3 of the spec](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3), the `aud` claim should usually be an array of strings, although it can also be just a string.

![Section 4.1.3 JWT Spec](https://github.com/pilcrowOnPaper/oslo/assets/28960614/82b2d9d4-2ad1-430d-8e5f-50ddc6ba7326)

Looking your library's source code, I noticed that it only supports `string` as the type of `audience`. Can you confirm if this was an intentional design decision? 

If not, I am happy to contribute by making a PR to resolve this issue.

**Comment by pilcrowonpaper** [comment]
Oh, TIL! Yeah this wasn't intentional.

As for the implementation/fix, maybe we should make `JWT.audience` always be an array instead of `string | string[]` so you wouldn't need to check for the type

**Comment by pilcrowonpaper** [comment]
Fixed with `0.26.0`
