### ISSUE TITLE
Adding function to convert uri into image

### ISSUE THREAD

**Issue by sheecet** [pilcrowOnPaper/oslo#20]
In this [link](https://v3.lucia-auth.com/guides/email-and-password/2fa) we have `const qrcode = createQRCode(uri);` as placeholders.  I had reviewed a few libraries to add an implemention to my project. I think this one is the most stable https://kazuhikoarase.github.io/qrcode-generator/js/demo/ and [pure js](https://github.com/kazuhikoarase/qrcode-generator/blob/master/js/qrcode.js). Using it is pretty straight forward I was wondering if I can add it as a function under `oslo/otp`

```
import { qrcode } from "$lib/qrcode"
var typeNumber = 0;
var errorCorrectionLevel = 'M';
var qr = qrcode(typeNumber, errorCorrectionLevel);
qr.addData(uri);
qr.make();
console.log(qr.createImgTag())

```

**Comment by pilcrowonpaper** [comment]
Similar to password hashing, it would be better to rely on something native to the runtime, and I'd rather not rely on WASM. I don't think it fits the library in the first place too
