### ISSUE TITLE
Dependency minimization

### ISSUE THREAD

**Issue by skyf0l** [pilcrowOnPaper/oslo#22]
`@node-rs/argon2` and `@node-rs/bcrypt` are only required by the password provider and pull many huge dependencies (with binaries).
Is it possible to make it optional and reduce the number of dependencies ?

**Comment by pilcrowonpaper** [comment]
You can't make dependencies optional. You should be bundling and tree shaking your project if need to reduce the size for serverless etc

**Comment by marcomuser** [comment]
@pilcrowOnPaper I think it is actually possible to make dependencies optional by using [peerDependenciesMeta](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta) in package.json. It would be possible to set both dependencies as optional peer dependencies and add a section to the [oslo/password](https://oslo.js.org/reference/password) documentation which explains that for this module @node-rs/argon2 and @node-rs/bcrypt need to be installed separately! The peerDependency version would still make sure that the required/tested version will be installed. I think this would be beneficial for everyone that does not require the password module. Would you be open for this?

**Comment by pilcrowonpaper** [comment]
@marcomuser I'd have to test it to make sure it works, but I'm open to the idea :D

That said, it would be a breaking change so I don't think we can commit to it yet

**Comment by marcomuser** [comment]
Sounds good! Then let's reopen this ticket. If you want to see how a published npm package with an optional peer dependency behaves check out [@tanstack/vue-query](https://github.com/TanStack/query/blob/55782aebbbc69020858f8ed611ab41d24eee215a/packages/vue-query/package.json#L78) as an example which has an optional peer dependency for users that still use it with vue v2. When installed as package from npm the optional peer dependency doesn't get added to node_modules automatically. But when you clone the repo and (p)npm install, it will get installed automatically for development as usual.

**Comment by pilcrowonpaper** [comment]
We're removing password hashing in v2
