### ISSUE TITLE
Hash password on edge?

### ISSUE THREAD

**Issue by osseonews** [pilcrowOnPaper/oslo#24]
I was reading the docs here for password functionality: https://oslo.js.org/reference/password/

It says, this requires Node APIs. If so, how would you hash a password in edge environment, like Cloudflare Workers or NextJs Edge/Middleware?

**Comment by pilcrowonpaper** [comment]
I would look into pure JS implementation of Scrypt like [`noble-hashes`](https://github.com/paulmillr/noble-hashes), though it'll be pretty slow compared to Node APIs
