### ISSUE TITLE
Why is Bcrypt not recommended?

### ISSUE THREAD

**Issue by pepper-lees** [pilcrowOnPaper/oslo#32]
[The documentation](https://oslo.js.org/reference/password/Bcrypt/) says that it's recommended to use Argon2id or Scrypt instead of bcrypt if possible, but does not explain why. What reason is it not recommended?

**Comment by pilcrowonpaper** [comment]
Bcrypt has a maximum input length of 56~72 bytes, and is [considered legacy](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet) by OWASP.
