### ISSUE TITLE
Vercel adapter not working with node-rs/bcrypt

### ISSUE THREAD

**Issue by sajaghori** [pilcrowOnPaper/oslo#47]
Currently I have an issue using the latest version of vercel adapter in my sveltekit app.

The message appears on prod build:
`Warning: The following modules failed to locate dependencies that may (or may not) be required for your app to work: ...`

I tested the node adapter and it seems to work fine with that.
Is there a way to fix it for vercel apps? I think vercel does not have all the node dependencies on their edge runtime: [vercel blog](https://vercel.com/guides/why-does-my-serverless-function-work-locally-but-not-when-deployed#native-dependencies)

They suggest to use a different library such as [bcrypt.js](https://github.com/dcodeIO/bcrypt.js)

**Comment by pilcrowonpaper** [comment]
1. Are you building serverless functions or edge
2. Did you actually test the app in prod? It's possible it's just a warning

**Comment by sajaghori** [comment]
1. I'm building serverless function
2. I tested it now and it seem like it's just a warning. I had another error causing issues with authentication. It works fine on Vercel.
