### ISSUE TITLE
Why is auri listed as a dependency

### ISSUE THREAD

**Issue by ilyashegay** [pilcrowOnPaper/oslo#50]
Auri is listed as dev dependency in lucia, but is a main dependency in both oslo and arctic. It is unused in prod code, and also installs 11 additional unused packages.

**Comment by pilcrowonpaper** [comment]
Auri is a package release manager for Oslo and Arctic.

**Comment by ilyashegay** [comment]
Can it be made a dev dependency, like in lucia? Is there a reason Auri needs to be installed when installing `npm install oslo` or `npm install arctic`?

**Comment by pilcrowonpaper** [comment]
Oh, didn't notice it *wasn't* a dev dependency - thanks!
