### ISSUE TITLE
Support Bearer authentication for OAuth token requests

### ISSUE THREAD

**Issue by m-radmacher** [pilcrowOnPaper/oslo#55]
If you enable certificate authentication instead of token authentication in Microsoft Entra ID, you must authenticate via a Bearer token. (see https://learn.microsoft.com/en-us/answers/questions/346048/how-to-get-access-token-from-client-certificate-ca)
This is currently not supported by oslo.

I have already begun implementing this option and it seems like a trivial change (https://github.com/pilcrowOnPaper/oslo/compare/main...m-radmacher:oslo:feat/oauth-jwt-authentication).

If you're interested in merging this I would probably need to update the docs further.

**Comment by pilcrowonpaper** [comment]
Closing this as out-of-scope - Oslo will only support authorization code grant type for OAuth
