### ISSUE TITLE
Incorrect maxAge in cookie

### ISSUE THREAD

**Issue by Ryiski** [pilcrowOnPaper/oslo#60]
I've been having this issue for the passed few days now where i am logged out when i open my application the next morning.

I found out the the `Expires / Max-Age` in the cookie is wrong even when i make `sessionCookie expires: false` in lucia, 

it is currently setting the `Expires / Max-Age` as seconds, when converted to milliseconds i works as expected
https://github.com/pilcrowOnPaper/oslo/blob/c1f60eca2137cda93bb7aefed35781d85d12c7b6/src/cookie/index.ts#L80

**Comment by pilcrowonpaper** [comment]
What framework are you using? This is a known issue in Express. Might be better to use `Expires` instead

**Comment by Ryiski** [comment]
i am using expressjs, and do you mean setting the `Expires` key manually on the cookie?

**Comment by pilcrowonpaper** [comment]
I meant that we should consider using Expires instead in Lucia. Though, this is expected behavior in Oslo. Can you open a new issue in Lucia to use `Expires` instead of `Max-Age`?
