### ISSUE TITLE
Error importing `oslo` in NestJS

### ISSUE THREAD

**Issue by basememara** [pilcrowOnPaper/oslo#66]
Having trouble using this package in a NestJS app, I guess because NestJS is still stuck on CommonJS unfortunately. Instead of importing like other packages, I do this inline in code:

```typescript
const { Argon2id } = await import('oslo/password');
const argon2id = new Argon2id();
const hash = await argon2id.hash(password);
```

However, I get the below error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/oslo/dist/password/index.js from /dist/api/auth/auth.service.js not supported.

Instead change the require of index.js in /dist/api/auth/auth.service.js to a dynamic import() which is available in all CommonJS modules.
```

That's what I'm doing above and tried many different variations. Anything else I can try or missing?

**Comment by pilcrowonpaper** [comment]
I'm going to close this since it's not an issue, but see guides like https://stackoverflow.com/questions/74830166/unable-to-import-esm-module-in-nestjs

I believe top-level await is an ESM feature
