### ISSUE TITLE
Create key from string

### ISSUE THREAD

**Issue by david-plugge** [pilcrowOnPaper/oslo#76]
Is there a way to create a key from a random string for signing and verifying jwts using oslo?
If not, how to do it?

My goal is to be able to specify a secret as an env variable that is used for handling jwts.

**Comment by david-plugge** [comment]
It was too early in the morning...

**Comment by practicatto** [comment]
@david-plugge did you solve this? how did you that?

**Comment by david-plugge** [comment]
Simply use `TextEncoder`
```ts
const JWT_KEY = new TextEncoder().encode(env.MAGIC_LINK_TOKEN_SECRET);

await createJWT(
	algorithm,
	JWT_KEY,
	{},
	{
		subject: email,
		expiresIn: new TimeSpan(10, 'm')
	}
);
```

**Comment by practicatto** [comment]
Yes silly me, thanks :)
