### ISSUE TITLE
Cant be deployed to serverless worker functions

### ISSUE THREAD

**Issue by MickL** [pilcrowOnPaper/oslo#77]
Using Oslo `1.2.0` I get an error when trying to deploy to Cloudflare Worker:

> [error] [nitro] Error: Cannot resolve "./argon2.darwin-universal.node" from "/opt/buildhome/repo/node_modules/@node-rs/argon2/index.js" and externals are not allowed!

I was importing:

```
import { Argon2id } from 'oslo/password';
```

**Comment by IndependentCreator** [comment]
> Using Oslo `1.2.0` I get an error when trying to deploy to Cloudflare Worker:

A potential alternative when deploying to cloudflare workers could be to use the web crypto functions:
https://developers.cloudflare.com/workers/runtime-apis/web-crypto/

**Comment by pilcrowonpaper** [comment]
This is expected. `oslo/password` only works in Node.js. You can use something like noble-hashes but in general I don't recommend hashing passwords in CF workers

https://github.com/paulmillr/noble-hashes

**Comment by MickL** [comment]
> I don't recommend hashing passwords in CF workers

Why exactly? Cloudflare implements their own crypto functions called [Web Crypto API](https://developers.cloudflare.com/workers/runtime-apis/web-crypto/) through the SubtleCrypto interface:

> Performing cryptographic operations using the Web Crypto API is significantly faster than performing them purely in JavaScript. If you want to perform CPU-intensive cryptographic operations, you should consider using the Web Crypto API.

**Comment by pilcrowonpaper** [comment]
The Web Crypto API is a web standard and it doesn't support algorithms for hashing passwords. Well it does support PBKDF2 but it's not very memory hard

**Comment by MickL** [comment]
The interface is a standard but the implementation is Cloudfares own and they support a lot of algorithms:

https://developers.cloudflare.com/workers/runtime-apis/web-crypto/#supported-algorithms

**Comment by pilcrowonpaper** [comment]
yeah like I said, out of those algorithms only PBKDF2 is suitable for hashing passwords but even then it's outdated
