### ISSUE TITLE
Add "ES384" as option of "codeChallengeMethod"

### ISSUE THREAD

**Issue by ggomarighetti** [pilcrowOnPaper/oslo#82]
I was trying to use the library to connect to my provider (Logto) and they use undisputedly the "ES384" algorithm, option that is not currently available in the "oauth2" project but inside the "crypto" project.

**Comment by pilcrowonpaper** [comment]
As far as I'm aware, this isn't part of any standard or a de facto standard. Oslo only intends to support standardized features
