### ISSUE TITLE
Add "audience" as option of "OAuth2Client"

### ISSUE THREAD

**Issue by ggomarighetti** [pilcrowOnPaper/oslo#84]
It would be great to be able to pass as an optional parameter an audience so that when building the different URLs it is already included.

**Comment by pilcrowonpaper** [comment]
The audience parameter of the authorization URL isn’t part of any OAuth or OIDC specification and such out of scope of the library

**Comment by ggomarighetti** [comment]
https://www.rfc-editor.org/rfc/rfc8707.html

**Comment by pilcrowonpaper** [comment]
The only parameter mentioned is the resource parameter?
