### ISSUE TITLE
Typo in alphabet documentation?

### ISSUE THREAD

**Issue by ivan-dalmet** [pilcrowOnPaper/oslo#88]
Thank a lot for this library!

I think there is a little typo on the A-Z documentation of alphabet
https://oslo.js.org/reference/crypto/alphabet

![image](https://github.com/user-attachments/assets/1486cec6-4d86-4745-9263-17190eeb8b16)
![image](https://github.com/user-attachments/assets/f0a76aa5-391b-461a-bc94-86b04385cfb7)

(If this is not a typo, maybe explaining why in the documentation 😅)

**Comment by pilcrowonpaper** [comment]
Fixed
